### PR TITLE
add api-ai-ruby as runtime_dependency and same changes to resolve build warnings

### PR DESCRIPTION
**Pull request by luizcarvalho**
add runtime_dependency api-ai-ruby 2.0
- Add version to all dependencies
- Change quotes to single quotes
- Change >= to ~>

### CODE REVIEW

**Comment by manicholls** [comment]
can you increment the version as well?

**Comment by luizcarvalho** [comment]
Oops, sorry. changed! :)

**Comment by manicholls** [comment]
Thanks, I've pushed the new Gem up as well.

**Comment by luizcarvalho** [comment]
Happy to contribute!

**Pull request merged**
